services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - icpt_network
    restart: "on-failure"

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - icpt_network
    restart: "on-failure"

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443" 
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - icpt_network
    restart: "on-failure"

volumes:
  mariadb_data:
    name: mariadb_data
    driver_opts:
      type : none
      device: /home/mbaptist/data/vol_db
      o: bind
  wordpress_data:
    name: wordpress_data
    driver_opts:
      type : none
      device: /home/mbaptist/data/vol_wp
      o: bind

networks:
  icpt_network:
    name: icpt_network
    driver: bridge
