services:
  mariadb:
    build: ./srcs/requirements/mariadb
    container_name: mariadb_test
    env_file:
      - .env
    # environment:
    #   MYSQL_DATABASE: ${MYSQL_DATABASE}
    #   MYSQL_USER: ${MYSQL_USER}
    #   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #   MYSQL_HOST: ${MYSQL_HOST}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - icpt_network
    restart: "on-failure"

  wordpress:
    build: ./srcs/requirements/wordpress
    container_name: wordpress_test
    depends_on:
      - mariadb
    env_file:
      - .env
    # environment:
    #   MYSQL_DATABASE: ${MYSQL_DATABASE}
    #   MYSQL_USER: ${MYSQL_USER}
    #   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #   MYSQL_HOST: ${MYSQL_HOST}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - icpt_network
    restart: "on-failure"

  nginx:
    build: ./srcs/requirements/nginx
    container_name: nginx_test
    depends_on:
      - wordpress
    ports:
      - "443:443" 
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - icpt_network
    restart: "on-failure"

volumes:
  mariadb_data:
    driver_opts:
      type : none
      device: /home/mbaptist/inception/vol_db #/home/struf/inception/vol_db
      o: bind
  wordpress_data:
    driver_opts:
      type : none
      device: /home/mbaptist/inception/vol_wp # /home/struf/inception/vol_wp
      o: bind

networks:
  icpt_network:
    name: icpt_network
    driver: bridge
