services:
  mariadb:
    build: ./srcs/requirements/mariadb
    container_name: mariadb_test
    secrets:
      - mysql_root_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - icpt_network
    restart: "on-failure"

  wordpress:
    build: ./srcs/requirements/wordpress
    container_name: wordpress_test
    depends_on:
      - mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - icpt_network
    restart: "on-failure"

  nginx:
    build: ./srcs/requirements/nginx
    container_name: nginx_test
    depends_on:
      - wordpress
    ports:
      - "8443:443" 
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - icpt_network
    restart: "on-failure"

volumes:
  mariadb_data:
    driver_opts:
      type : none
      device: /home/struf/inception/vol_db # /home/mbaptist/inception/vol_db
      o: bind
  wordpress_data:
    driver_opts:
      type : none
      device: /home/struf/inception/vol_wp # /home/mbaptist/inception/vol_wp
      o: bind

networks:
  icpt_network:
    driver: bridge

secrets:
  mysql_root_password:
    file: ./mysql_root_password.txt